# Generated by Django 4.2.25 on 2025-10-26 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consume",
            options={"ordering": ["-date_consumed", "-time_consumed"]},
        ),
        migrations.AddField(
            model_name="consume",
            name="date_consumed",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="consume",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                ],
                default="snack",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consume",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consume",
            name="servings",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="consume",
            name="time_consumed",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="food",
            name="fiber",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="food",
            name="serving_size",
            field=models.CharField(default="100g", max_length=50),
        ),
        migrations.AddField(
            model_name="food",
            name="sugar",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="WeightLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(help_text="Weight in kg")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "height",
                    models.FloatField(blank=True, help_text="Height in cm", null=True),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary (little or no exercise)"),
                            (
                                "light",
                                "Lightly active (light exercise/sports 1-3 days/week)",
                            ),
                            (
                                "moderate",
                                "Moderately active (moderate exercise/sports 3-5 days/week)",
                            ),
                            (
                                "very",
                                "Very active (hard exercise/sports 6-7 days/week)",
                            ),
                            (
                                "super",
                                "Super active (very hard exercise & physical job or training twice per day)",
                            ),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "weight_goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        default="maintain",
                        max_length=10,
                    ),
                ),
                ("daily_calorie_goal", models.IntegerField(default=2000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
