# Generated by Django 4.2.25 on 2025-10-26 20:55

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('myapp', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_consume_options_consume_date_consumed_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_func),
    ]
