# Generated by Django 5.2.8 on 2025-11-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Phone number", max_length=15, null=True
            ),
        ),
    ]
