# Generated by Django 5.2.8 on 2025-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(blank=True, help_text="Weight in kg", null=True),
        ),
    ]
